name: Pipeline with Jest Test
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

  tests:
    runs-on: ubuntu-22.04
    needs: build # Test-Job wartet, bis der Build-Job erfolgreich ist
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies and run Test
      run: npm install

    - name: run tests
      run: npm test
